mlflow_params:
  uri: https://dagshub.com/RajeshGoldy/blood_group_detection.mlflow

image_params:
  height: 100
  width: 96
  channels: 1
  no_categories: 8
  
  
  # image transformation params: src/config/configuration/ImageTransformationConfig
image_transformation:
  height: 100
  width: 96
  mean: 0
  std: 1
  batch_size: 2
  shuffle: True
  workers: 0

train_model: #  Used in src/models/training.py
  basemodule: src.models.vanilla # change vanilla to other module 
  submodule: model # this will remain constant
  modelclass: VanillaModel # class in module
  optimizer: Adam
  optimizer_args:
    lr: 0.01

  criterion: "CrossEntropyLoss"

training:
  epochs: 2
  batch_size: 2